### ISSUE TITLE
Add usage info on calling --help/-h

### ISSUE THREAD

**Issue by zxqfox** [nodejs/changelog-maker#10]
There are no errors on passing wrong arguments or in wrong order or passing unknown flags, params.

Can we implement something?

`--usage` (for short) and `--help`/`-?` for more detailed help would be enough.

**Comment by rvagg** [comment]
go for it!

**Comment by XhmikosR** [comment]
@rvagg isn't this sorted? I see there's code which reads README.md and outputs the info.
