### ISSUE TITLE
coloring is broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/changelog-maker#120]
https://github.com/nodejs/changelog-maker/pull/98 has broken coloring of changelog entries in a terminal.

e.g. with current `v14.x-staging`
![image](https://user-images.githubusercontent.com/5445507/144478359-0d4b5eb7-2851-4313-bfdb-835c9809684c.png)

expected (with changelog-maker@2.6.0)
![image](https://user-images.githubusercontent.com/5445507/144478536-d6a830d4-1c6d-4c80-8e08-fb8a11a5ae40.png)

It looks like the formatting is corrupting the ansi escape codes. Both @BethGriggs and I ran into this preparing the most recent releases and we had to manually remove the corrupted ansi when pasting into the changelogs.

I guess we could `stripAnsi()` before formatting but then we'd lose the coloring completely.

cc @Trott

**Comment by Trott** [comment]
Hopefully the fix is an options setting in `remark-stringify` or something simple like that...

**Comment by richardlau** [comment]
Could we move the formatting into `commit-to-output.js`?
https://github.com/nodejs/changelog-maker/blob/caeeabd3270eb07206b74656ded38a8d3573fe7d/commit-to-output.js#L74-L91

I had a go but got really confused trying to call the asynchronous format from a sync function.

**Comment by Trott** [comment]
The text color doesn't end up in our changelogs, website release notes/announcements, or anywhere else as far as I can tell. Is that correct? It's just for the terminal output of the person running the command? If so, a simple workaround (at least temporarily) is to add the `--simple` flag.
