### ISSUE TITLE
bug: incorrect author attribution when base branch is force pushed

### ISSUE THREAD

**Issue by danielleadams** [nodejs/changelog-maker#133]
When a changelog is generated, there is an instance when the incorrect author is listed.

#### Steps for reproduction:
- commit author opens a pull request against a base branch
- a second person force pushes to base branch
- commit author rebases on base branch
- second person is added as a co-author on the commit
- when the changelog is generated, the second person that has been added as co-author is listed as the author

#### Expected result:
When the changelog is generated, the commit author should be listed as the author.

**Comment by targos** [comment]
Do you have an example PR for which it happened?

**Comment by RafaelGSS** [comment]
I think the issue might be on `git node land` who included the wrong metadata. Just a guess. 

@targos this one https://github.com/nodejs/node/pull/44256

**Comment by targos** [comment]
I don't think this is related to our tooling. The PR author probably did a mistake when they rebased.

**Comment by danielleadams** [comment]
Okay, I can close then.
