### ISSUE TITLE
Add url for nongithub repositories

### ISSUE THREAD

**Issue by sergeysova** [nodejs/changelog-maker#32]
I have repositories in bitbucket and gitlab.
I want:

``` bash
changelog-maker --url=http://git.lestad.net game src
```

and in result:

```
* [[`123abc456`](http://git.lestad.net/game/src/commit/123abc456)] - **label**: commit text (lestad)
```

**Comment by ralphtheninja** [comment]
@LestaD Code it and make a PR :)

**Comment by rvagg** [comment]
I'd be concerned that it relies too much on the same github url structure for commits, maybe it should be a template: `--commit-url=http://git.lestad.net/game/src/commit/{sha}`? I'm not sure the project org and name make much sense outside of github so maybe not require them in this case.

But as @ralphtheninja suggests, this will probably only happen if you send us a PR to get started.

**Comment by jimniels** [comment]
@sergeysova @rvagg @ralphtheninja I went ahead and created a solution via #55 based on your conversation here.
