### ISSUE TITLE
URLs with trailing / doesn't work

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/changelog-maker#50]
https://github.com/nodejs/node/commit/562d445999

Notice the PR-URL has a trailing / and it breaks all the things

**Comment by targos** [comment]
I think this is where we should add support for trailing "/": https://github.com/nodejs/commit-stream/blob/master/commit-stream.js#L46-L56

**Comment by gibfahn** [comment]
cc/ @nodejs/automation , if anyone would like to take a look at that it would be very helpful!
