### ISSUE TITLE
Document the requirements to get this running

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/changelog-maker#65]
What's needed to make tests work locally with exact steps like the config path, the token permissions, etc.

Note that for me on Windows, running `node changelog-maker.js` I don't get asked for credentials or anything. So, when I do `npm t` it just fails.

**Comment by rvagg** [comment]
> running node changelog-maker.js I don't get asked for credentials 

Are you running it in a repo with `PR-URL` in commits? I think that's the path to collecting label data which requires the authentication. If you're running it on a repo without that metadata then I don't think it needs to contact GH.

But yes, docs needed, and I should try running it on Windows myself I guess.
