### ISSUE TITLE
SuArtChangelog.ms

### ISSUE THREAD

**Issue by SuatAkbuetuen** [nodejs/changelog-maker#91]
https://www.github.com/d4rken/sdmaid-public/tree/master/CHANGELOG.md

**Comment by rvagg** [comment]
@nodejs/moderation I'd really like a block on this user please. Just for this repo, or for the org, whatever. I don't know what this is, it looks like a bot, but there's been a slow drip of these (usually content free) issues opened on this repo. I've deleted a couple of issues and closed others. See https://github.com/nodejs/changelog-maker/issues?q=author%3ASuatAkbuetuen for the ones I've left.

**Comment by benjamingr** [comment]
@rvagg I will comment in a moderation repo issue and ping you there. Thanks for the ping.
